# Generated by Django 5.2.12 on 2026-03-31 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Velhinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('idade', models.IntegerField()),
                ('sexo', models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino')], max_length=1)),
                ('doencas', models.CharField(max_length=300)),
                ('daily_step_goal', models.IntegerField(default=2000)),
                ('center_lat', models.FloatField()),
                ('center_lng', models.FloatField()),
                ('radius', models.IntegerField(default=500)),
                ('lar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geoelder.lar')),
            ],
        ),
        migrations.CreateModel(
            name='Localizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('passos', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('velhinho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geoelder.velhinho')),
            ],
        ),
    ]
