# Generated by Django 5.2.12 on 2026-03-31 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoelder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='velhinho',
            name='center_lat',
        ),
        migrations.RemoveField(
            model_name='velhinho',
            name='center_lng',
        ),
        migrations.RemoveField(
            model_name='velhinho',
            name='radius',
        ),
        migrations.AddField(
            model_name='lar',
            name='center_lat',
            field=models.FloatField(default=41.3333),
        ),
        migrations.AddField(
            model_name='lar',
            name='center_lng',
            field=models.FloatField(default=-8.2354),
        ),
        migrations.AddField(
            model_name='lar',
            name='radius',
            field=models.IntegerField(default=500),
        ),
    ]
